---@meta

---Plugin config state.
---@class pyrepl.Config
---@field split_horizontal boolean
---@field split_ratio number
---@field style string
---@field style_treesitter boolean
---@field image_max_history integer
---@field image_width_ratio number
---@field image_height_ratio number
---@field image_provider string
---@field cell_pattern string|fun(): string
---@field python_path string|nil
---@field preferred_kernel string|nil
---@field jupytext_hook boolean

---Plugin setup opts (all arguments are optional).
---@class pyrepl.ConfigOpts
---@field split_horizontal? boolean
---@field split_ratio? number
---@field style? string
---@field style_treesitter? boolean
---@field image_max_history? integer
---@field image_width_ratio? number
---@field image_height_ratio? number
---@field image_provider? "placeholders" | "image" | string
---@field cell_pattern? string|fun(): string
---@field python_path? string
---@field preferred_kernel? string
---@field jupytext_hook? boolean

---Image provider interface.
---@class pyrepl.Image
---@field create fun(img_base64: string): pyrepl.Image|nil
---@field render fun(self: pyrepl.Image, buf: integer, win: integer)
---@field clear fun(self: pyrepl.Image)
---@field delete fun(self: pyrepl.Image)

---@class pyrepl.ReplState
---@field closing boolean
---@field chan integer
---@field kernel string
---@field buf integer
---@field win integer|nil

---@class pyrepl.ImageHistoryState
---@field closing boolean
---@field history pyrepl.Image[]
---@field idx integer
---@field buf integer|nil
---@field win integer|nil
